/**
 * ReadmeGenerator — writes a stack-specific README.md at the project root.
 *
 * Architectural decision:
 * README content is derived from ProjectConfig in code (not a single mega-
 * template with dead branches) so Express+Prisma docs never mention FastAPI,
 * and MongoDB instructions never show createdb.
 */

import path from "node:path";

import fs from "fs-extra";

import type { ProjectConfig } from "../types/index.js";
import type { Generator, GeneratorContext } from "./types.js";

export class ReadmeGenerator implements Generator {
  readonly id = "readme";
  readonly label = "README";

  supports(_config: ProjectConfig): boolean {
    return true;
  }

  async generate(context: GeneratorContext): Promise<void> {
    const readme = buildReadme(context.config, context.variables);
    await fs.writeFile(path.join(context.paths.root, "README.md"), readme, "utf8");
  }
}

function buildReadme(
  config: ProjectConfig,
  vars: GeneratorContext["variables"],
): string {
  const name = vars.PROJECT_NAME;
  const lines: string[] = [];

  lines.push(`# ${name}`);
  lines.push("");
  lines.push(
    `Generated by [create-vistaar](https://github.com/). This README matches your selected stack.`,
  );
  lines.push("");
  lines.push("## Project Overview");
  lines.push("");
  lines.push(`| Piece | Choice |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Frontend | ${vars.FRONTEND} (${vars.LANGUAGE}) |`);
  lines.push(`| UI | ${vars.UI_FRAMEWORK} |`);
  lines.push(`| Backend | ${vars.BACKEND} |`);
  lines.push(`| Database | ${vars.DATABASE} |`);
  lines.push(`| ORM / driver | ${vars.ORM} (\`${vars.DB_DRIVER}\`) |`);
  lines.push(`| Authentication | ${vars.AUTHENTICATION} |`);
  lines.push(`| Docker | ${vars.DOCKER} |`);
  lines.push("");
  lines.push("## Requirements");
  lines.push("");
  lines.push("- Node.js 18+");
  if (config.backend === "fastapi") {
    lines.push("- Python 3.10+");
  }
  if (config.database === "postgresql") {
    lines.push("- PostgreSQL");
  }
  if (config.database === "mongodb") {
    lines.push("- MongoDB");
  }
  if (config.docker) {
    lines.push("- Docker + Docker Compose (optional but enabled for this project)");
  }
  lines.push("");
  lines.push("## Installation");
  lines.push("");
  lines.push("```bash");
  lines.push("npm run setup");
  lines.push("```");
  lines.push("");
  lines.push("Or install packages manually:");
  lines.push("");
  lines.push("```bash");
  lines.push("npm install --prefix frontend");
  if (config.backend === "express") {
    lines.push("npm install --prefix backend");
  } else if (config.backend === "fastapi") {
    lines.push("cd backend && python -m venv .venv && pip install -r requirements.txt");
  }
  if (config.authentication === "base-auth") {
    lines.push("npm install --prefix auth-api");
  }
  lines.push("```");
  lines.push("");
  lines.push("Then open the Setup Wizard at the frontend URL and follow the steps.");
  lines.push("");

  lines.push("## Database Setup");
  lines.push("");
  if (config.database === "postgresql") {
    lines.push(`Database name: \`${vars.DB_NAME}\``);
    lines.push("");
    lines.push("```bash");
    lines.push(`createdb ${vars.DB_NAME}`);
    lines.push("```");
    lines.push("");
    lines.push("Or SQL:");
    lines.push("");
    lines.push("```sql");
    lines.push(`CREATE DATABASE ${vars.DB_NAME};`);
    lines.push("```");
    lines.push("");
    lines.push("Copy `backend/.env.example` to `backend/.env` and set `DATABASE_URL`.");
    lines.push("");
    lines.push("```bash");
    lines.push("npm run migrate");
    lines.push("npm run seed");
    lines.push("```");
  } else if (config.database === "mongodb") {
    lines.push(
      "MongoDB creates the database automatically when the first document is inserted. No manual `CREATE DATABASE` step is required.",
    );
    lines.push("");
    lines.push("Copy `backend/.env.example` to `backend/.env` and set `MONGODB_URI`.");
    lines.push("");
    lines.push("```bash");
    lines.push("npm run seed");
    lines.push("```");
  } else {
    lines.push(
      "No external database was selected. The API uses a local file store for AppInfo so the Welcome Dashboard still works end-to-end.",
    );
  }
  lines.push("");

  lines.push("## Environment Variables");
  lines.push("");
  lines.push("| Variable | Where | Purpose |");
  lines.push("| --- | --- | --- |");
  lines.push("| `PORT` | backend | API port (default `3000`) |");
  lines.push("| `DB_DRIVER` | backend | Persistence driver |");
  if (config.database === "postgresql") {
    lines.push("| `DATABASE_URL` | backend | Postgres connection string |");
  }
  if (config.database === "mongodb") {
    lines.push("| `MONGODB_URI` | backend | Mongo connection string |");
  }
  lines.push("| `CORS_ORIGIN` | backend | Allowed frontend origin |");
  lines.push("| `VITE_API_URL` | frontend | Optional absolute API base (proxy used by default) |");
  lines.push("");

  lines.push("## Running the Project");
  lines.push("");
  lines.push("```bash");
  lines.push("# terminal 1");
  lines.push("npm run dev:backend");
  lines.push("");
  lines.push("# terminal 2");
  lines.push("npm run dev:frontend");
  lines.push("```");
  lines.push("");
  lines.push(`- Frontend: ${vars.FRONTEND_URL}`);
  lines.push(`- Backend health: ${vars.API_URL}/api/health`);
  lines.push(`- Setup status: ${vars.API_URL}/api/setup-status`);
  if (config.backend === "fastapi") {
    lines.push(`- Swagger: ${vars.API_URL}/docs`);
  }
  lines.push("");

  if (config.docker) {
    lines.push("### Docker");
    lines.push("");
    lines.push("```bash");
    lines.push("docker compose up -d");
    lines.push("```");
    lines.push("");
  }

  lines.push("## Useful Commands");
  lines.push("");
  lines.push("| Command | Description |");
  lines.push("| --- | --- |");
  lines.push("| `npm run setup` | Install guidance + doctor |");
  lines.push("| `npm run doctor` | Verify environment & services |");
  lines.push("| `npm run migrate` | Run database migrations / schema push |");
  lines.push("| `npm run seed` | Seed AppInfo |");
  lines.push("| `npm run reset-db` | Clear local setup markers / file store |");
  lines.push("| `npm run dev:frontend` | Start Vite |");
  lines.push("| `npm run dev:backend` | Start API |");
  lines.push("");

  lines.push("## Folder Structure");
  lines.push("");
  lines.push("```");
  lines.push(`${vars.PACKAGE_NAME}/`);
  lines.push("  frontend/     React app + Setup Wizard + Welcome Dashboard");
  if (config.backend !== "none") {
    lines.push("  backend/      API (/api/app-info, /api/health, /api/setup-status)");
  }
  if (config.database !== "none") {
    lines.push("  database/     DB notes + .env.example");
  }
  lines.push("  scripts/      setup, doctor, start, reset-db helpers");
  lines.push("```");
  lines.push("");

  lines.push("## Troubleshooting");
  lines.push("");
  lines.push("- **Setup Wizard stuck on backend** — run `npm run dev:backend`, then refresh.");
  lines.push("- **Database disconnected** — check `.env`, create the DB, run `npm run migrate`.");
  lines.push("- **Seed pending** — run `npm run seed` or restart the API (auto-seeds when empty).");
  lines.push("- **Doctor warnings** — run `npm run doctor` for a full checklist.");
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(`Created with create-vistaar on ${vars.CREATED_AT}.`);
  lines.push("");

  return lines.join("\n");
}
